### ISSUE TITLE
Feature request: Copy any lua files found in source directory into build directory

### ISSUE THREAD

**Issue by svermeulen** [teal-language/cyan#19]
I find that it is common for some projects to have some portion of the code in lua.  It can be convenient to have these lua files saved alongside teal files in the same source directory.  I wonder if cyan could also copy those files over to the output directory too?  Or provide an option to do that?  I'm doing this as a second step after `cyan build --prune` but it's not ideal since it copies the lua files every time

**Comment by euclidianAce** [comment]
Implemented in d6282c39c387bedbf1264c4aac76f6b1c6f9c205!
