### ISSUE TITLE
cyan build: -b, --build-dir and -s, --source-dir flags?

### ISSUE THREAD

**Issue by hishamhm** [teal-language/cyan#24]
Would it be a good idea to add those flags `-b, --build-dir` and `-s, --source-dir` flags to `cyan build` to make it more of a drop-in replacement to `tl build`? I'm looking forward to removing `tl build` in the near future and directing users to `cyan build` instead.

**Comment by euclidianAce** [comment]
It does make sense to have these options for ease of transitioning from `tl build` to `cyan build` and they'd be pretty easy to implement.
