### ISSUE TITLE
Ability to ignore certain files in the build directory

### ISSUE THREAD

**Issue by lewis6991** [teal-language/cyan#25]
I currently commit my build directory into git and have a `README.md` file with the contents:

```
**WARNING**: Do not edit the files in this directory. The files are generated from [teal](https://github.com/teal-language/tl). For the original source files please look in the [teal](../teal) directory.
```

However, this file causes cyan to ~error out~ emit a warning.

It would be ideal if cyan could simply ignore non-`*.tl` files, or alternatively have a way to explicitly ignore particular files.

**Comment by euclidianAce** [comment]
> However this file causes cyan to error out.

Error out as in crashing? Trying to reproduce this just gives me the `--prune` warning.

**Comment by lewis6991** [comment]
No not crashing. Just a user error.

**Comment by lewis6991** [comment]
```
     Warn Unexpected files in build directory:
      ...    README.md
      ... hint: use `cyan build --prune` to automatically delete these files
```

**Comment by lewis6991** [comment]
Sorry, "erroring" was the wrong word. I just saw yellow in my terminal and assumed it didn't like it.

Either way, being able to suppress this warning would be ideal.
